# Generated by Django 3.2.20 on 2024-11-06 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dig',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
