# Generated by Django 3.2.20 on 2024-11-19 00:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20241106_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='traildig',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
