# Generated by Django 3.2.20 on 2024-11-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_traildig_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traildig',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
