# Generated by Django 3.2.20 on 2024-11-19 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_traildig_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traildig',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
